/** The validation schema for every journal table, used to check backups before they are restored. */
import type { z } from "zod";
import {
  accountSettingsSchema,
  aiConversationSchema,
  aiMessageSchema,
  aiReviewSchema,
  appSettingsSchema,
  assetSchema,
  changeHistorySchema,
  forecastRevisionSchema,
  forecastSchema,
  forecastTradeLinkSchema,
  levelInteractionSchema,
  marketSnapshotSchema,
  psychologyEntrySchema,
  reviewFindingSchema,
  reviewSchema,
  ruleCheckSchema,
  ruleGroupSchema,
  ruleSchema,
  screenshotAnnotationVersionSchema,
  setupMergeHistorySchema,
  setupRuleSchema,
  setupSchema,
  tradeEventSchema,
  tradeSchema,
  tradeScreenshotSchema,
  trashItemSchema,
} from "@/lib/domain/schemas";

export const TABLE_SCHEMAS: Readonly<Record<string, z.ZodType>> = {
  trades: tradeSchema,
  tradeEvents: tradeEventSchema,
  psychologyEntries: psychologyEntrySchema,
  screenshots: tradeScreenshotSchema,
  annotationVersions: screenshotAnnotationVersionSchema,
  assets: assetSchema,
  setups: setupSchema,
  setupRules: setupRuleSchema,
  setupMergeHistory: setupMergeHistorySchema,
  rules: ruleSchema,
  ruleGroups: ruleGroupSchema,
  ruleChecks: ruleCheckSchema,
  forecasts: forecastSchema,
  forecastRevisions: forecastRevisionSchema,
  marketSnapshots: marketSnapshotSchema,
  levelInteractions: levelInteractionSchema,
  forecastTradeLinks: forecastTradeLinkSchema,
  reviews: reviewSchema,
  reviewFindings: reviewFindingSchema,
  aiReviews: aiReviewSchema,
  aiConversations: aiConversationSchema,
  aiMessages: aiMessageSchema,
  changeHistory: changeHistorySchema,
  trashItems: trashItemSchema,
  accountSettings: accountSettingsSchema,
  appSettings: appSettingsSchema,
};
